server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment-routh
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**
        - id: payment-routh2
            uri: http://localhost:8001
            predicates:
              - Path=/payment/lb/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: cloud-gate-service